### ISSUE TITLE
Adding to the config disables the mod.

### ISSUE THREAD

**Issue by MattB70** [infernalexp/Food-Effects#4]
I am having trouble adding more foods to the config. When I add a modded item (for example: "tconstruct:earth_cake"), when I launch the game, the item is replaced by "minecraft:air" in the config. As expected this means I cannot add new foods to the list. Unexpectedly though, it also seems to make the other default food effects not work.

It seems that adding new foods to the list causes the config to be modified during runtime and causes the mod to stop working.

Added to config:
```toml
[[effects]]
	# Determines how long the effect lasts. If set to 0, the effect will be removed.
	# Range: [0, 1000000]
	duration = 2.0
	# Determines what item this effect is applied to.
	item = "tconstruct:earth_cake"
	# Determines how strong the effect is. Amplifiers start at 0.
	# Range: [0, 255]
	amplifier = 100
	# Determines what effect consuming the item will give in addition to any existing effects.
	effect = "minecraft:regeneration"
```

After running the game:
```toml
[[effects]]
	# Determines how long the effect lasts. If set to 0, the effect will be removed.
	# Range: [0, 1000000]
	duration = 2.0
	# Determines what item this effect is applied to.
	item = "minecraft:air"
	# Determines how strong the effect is. Amplifiers start at 0.
	# Range: [0, 255]
	amplifier = 100
	# Determines what effect consuming the item will give in addition to any existing effects.
	effect = "minecraft:regeneration"
```

The item variable line is the only difference, the rest of the config remains the same.
